AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: This application create a CFN dashboard with CPU and disks usage for every EC2 instances.
Parameters: 
    DashboardNameParameter: 
      Type: String
      Default: ec2-usage-report
    WidgetMinHeightParameter:
      Type: String
      Default: 4
    WidgetWidthParameter:
      Type: String
      Default: 12
Resources:
  
  CreateDashboardFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: create-dashboard
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: This Lambda build the report's dashboard
      MemorySize: 512
      Timeout: 7
    Environment:
      Variables:
        dashboard_name: !Ref DashboardNameParameter
        widget_min_height: !Ref WidgetMinHeightParameter
        widget_width: !Ref WidgetWidthParameter

  CreateDashboardRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: 'Allow'
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: '/'
      Policies:
        -
          PolicyName: create-dashboard-policies
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Sid: 'DescribeInstances'
                Action:
                  - 'ec2:DescribeInstances'
                Effect: Allow
                Resource:
                  - '*'
              -
                Sid: 'PutDashboard'
                Action:
                  - 'cloudwatch:PutDashboard'
                Effect: Allow
                Resource:
                  - '*'