AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: This application create a CFN dashboard with CPU and disks usage for every EC2 instances.

Metadata:
  AWS::ServerlessRepo::Application:
    Name: ec2-usage-report
    Description: This application create a CFN dashboard with CPU and disks usage for every EC2 instances.
    Author: Mariano Calandra
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['serverless', 'ec2-report']
    HomePageUrl: https://github.com/marianoc84/ec2-usage-report
    SemanticVersion: 1.0.12
    SourceCodeUrl: https://github.com/marianoc84/ec2-usage-report

Parameters: 
  DashboardNameParameter: 
    Type: String
    Default: ec2-usage-report
    Description: 'The name of Dashboard in CloudWatch'
  WidgetMinHeightParameter:
    Type: Number
    Default: 4
    Description: 'The height of the smallest widget'
  WidgetWidthParameter:
    Type: Number
    Default: 12
    Description: "Widget's width"

Resources:
  CreateDashboardFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: create-dashboard
      Handler: index.handler
      Role: !GetAtt CreateDashboardRole.Arn
      Runtime: nodejs8.10
      CodeUri: .
      Description: This Lambda build the report's dashboard
      MemorySize: 512
      Timeout: 7
      Environment:
        Variables:
          dashboard_name: !Ref DashboardNameParameter
          widget_min_height: !Ref WidgetMinHeightParameter
          widget_width: !Ref WidgetWidthParameter

  CreateDashboardRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: 'Allow'
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: '/'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        -
          PolicyName: create-dashboard-policies
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Sid: 'DescribeInstances'
                Action:
                  - 'ec2:DescribeInstances'
                Effect: Allow
                Resource:
                  - '*'
              -
                Sid: 'PutDashboard'
                Action:
                  - 'cloudwatch:PutDashboard'
                Effect: Allow
                Resource:
                  - '*'